import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import prisma from '../lib/prisma';
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { useRouter } from "next/router";
import React from "react";
import Button from '@mui/material/Button';
import FitbitHelper from "../lib/FitbitHelper.mjs";
import { inspect } from 'util';

const { DateTime } = require("luxon");



export async function getServerSideProps(ctx) {
    const session = await getSession(ctx);
  //const { encodedId, accessToken, dateTimeStr } = query;

  const user = await prisma.users.findFirst({
    where: { username: session.user.name },
  });

  let targetDate = DateTime.fromISO("2022-03-10");

  const activityResult = await FitbitHelper.getActvitySummaryAtDateForFitbitId(user.fitbitId, user.accessToken, targetDate)
    .then((responseData) => {
      console.log(
        `FitbitHelper.getActvitySummaryAtDateForFitbitId: ${JSON.stringify(
          responseData
        )}`
      );

      /*
      if(responseData.status == 400){
          // cannot auth: Bad Request
          // I supposed this mean we need to authenticate again
      }
      */

      //accessToken = responseData.access_token;

      // If you followed the Authorization Code Flow, you were issued a refresh token. You can use your refresh token to get a new access token in case the one that you currently have has expired. Enter or paste your refresh token below. Also make sure you enteryour data in section 1 and 3 since it's used to refresh your access token.
      //refreshToken = responseData.refresh_token;

      // To Do: ideally, store both
      //updateToken(hashCode, accessToken, refreshToken);

      return {value: "success", data: responseData};

      //res.status(200).json({ message: "authentication success" });
    })
    .catch((error) => {
      if (error.response) {
        // The request was made and the server responded with a status code
        // that falls out of the range of 2xx
        console.log(`Data: ${error.response.data}`);
        console.log(`Status: ${error.response.status}`);
        console.log(`StatusText: ${error.response.statusText}`);
        console.log(`Headers: ${error.response.headers}`);

        console.log(`Error response`);
        // which means, authentication falil
      } else if (error.request) {
        // The request was made but no response was received
        // `error.request` is an instance of XMLHttpRequest in the browser and an instance of
        // http.ClientRequest in node.js
        console.log(error.request);

        console.log(`Error request`);
      } else {
        // Something happened in setting up the request that triggered an Error
        // console.log('Error', error.message);

        console.log("Error else");
      }
      //res.status(error.response.status).json({ response: inspect(error.response.data) });

      let resultObj = eval(`(${inspect(error.response.data)})`);
      return {value: "failed", data: resultObj};
    });


  return {
    props: { result: activityResult, dateString: targetDate.toISO()},
  };
}

export default function ActivitySummary({result, dateString}) {
  const { data: session, status } = useSession();
  const router = useRouter();

  if (status == "loading") return <div>loading...</div>;
  if (!session){
    router.push('/');
    return null;
  }

  console.log(`session: ${JSON.stringify(session)}`);


  let message = "";

  let briefDateString = dateString; //DateTime.fromISO(dateString).toISODate();

  if(result.value == "failed"){
    message = `Fail to get activity summary for ${briefDateString}!\n`;
  }
  else{
    message = `Succeed to get activity summary ${briefDateString}!\n`;
  }


  console.log(`result.data: ${result.data}`);
  console.log(`typeof result.data: ${typeof result.data}`);

  let resultData = result.data;
  let hasAuthorizationError = false;

  console.log(`result Data type: ${typeof resultData}`);

  if(result.value == "failed" && resultData.errors[0].message.includes("Authorization Error")){
    hasAuthorizationError = true;
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Walk To Joy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <h1 className={styles.title}>{message}</h1>
        <div>
            {result.value == "success"? <h2>Steps: {resultData.summary.steps}</h2>:null}
        </div>
        <div>
            {
                JSON.stringify(result.data)
            }
        </div>
        <div>
            {
                result.value == "failed"? `Error: ${resultData.errors[0]["errorType"]}`: null
            }
        </div>
        <div>
            {
                result.value == "failed" && resultData.errors[0]["errorType"] == "expired_token"? 
                
                <Button variant="contained" onClick={(event) => {
                  router.push("/refresh-token");
                  return;
                }} >Refresh token</Button>
                :null
            }
        </div>
        <br />
        <br />
        <div>
            {
                result.value == "failed" && resultData.errors[0]["errorType"] == "invalid_token"? <div>Please connect your Fitbit in Settings.</div>:null
            }
        </div>
        <br />
        <br />

        <Button variant="contained" onClick={(event) => {
            router.push("/main");
            return;
          }} >Return to settings</Button>

      </main>

      <footer className={styles.main}>
        <div>WalkToJoy Study</div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div>School of Information</div>
          <div>University of Michigan</div>
        </a>
      </footer>
    </div>
  );
}
