import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
/*
import logger from "../lib/logger";

*/

import { Button } from "@mui/material";

import { inspect } from "util";

import Link from "next/link";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { useRouter } from "next/router";
import React, { useState } from "react";
import Divider from "@mui/material/Divider";
import Table from "@mui/material/Table";
import TableBody from "@mui/material/TableBody";
import TableCell from "@mui/material/TableCell";
import TableContainer from "@mui/material/TableContainer";
import TableHead from "@mui/material/TableHead";
import TableRow from "@mui/material/TableRow";
import Paper from "@mui/material/Paper";

import ToggleButton from "@mui/material/ToggleButton";
import ToggleButtonGroup from "@mui/material/ToggleButtonGroup";

import prisma from "../lib/prisma.mjs";

import SurveyResponseTable from "../component/SurveyResponseTable";
import FitbitSubscriptionTable from "../component/FitbitSubscriptionTable";
import TaskLogTable from "../component/TaskLogTable";
import MessageTable from "../component/MessageTable";

function replacer(key, value) {
  if (typeof value === "Date") {
    return value.toString();
  }
  return value;
}

const adminUsernameList = ["test1", "test2", "test3", "test4"];

export async function getServerSideProps(ctx) {
  const session = await getSession(ctx);
  console.log(`main.getServerSideProps: session: ${JSON.stringify(session)}`);

  if (!session) {
    return {
      props: {},
    };
  }

  let userName = session.user.name;


  const aUser = await prisma.users.findFirst({
    where: { username: userName },
  });

  let userInfo = JSON.parse(JSON.stringify(aUser, replacer));

  let responseList = [];
  let responseInfoList = [];
  

  let fitbitNotificationList = [];
  let fitbitNotificationInfoList = [];

  let taskLogList = [];
  let taskLogInfoList = [];

  let messageList = [];
  let messageInfoList = [];

  if (adminUsernameList.includes(userName)) {
    responseList = await prisma.response.findMany({
      /*
        select:{
            name: true,
            email: true,
            createdAt: true,
            updatedAt: true
        },
        */
      orderBy: [
        {
          updatedAt: "desc",
        },
      ],
    });

    responseInfoList = JSON.parse(JSON.stringify(responseList, replacer));
  }

  if (adminUsernameList.includes(userName)) {
    fitbitNotificationList = await prisma.fitbit_update.findMany({
      orderBy: [
        {
          updatedAt: "desc",
        },
      ],
    });

    fitbitNotificationInfoList = JSON.parse(JSON.stringify(fitbitNotificationList, replacer));
  }


  if (adminUsernameList.includes(userName)) {
    fitbitNotificationList = await prisma.fitbit_update.findMany({
      orderBy: [
        {
          updatedAt: "desc",
        },
      ],
    });

    fitbitNotificationInfoList = JSON.parse(JSON.stringify(fitbitNotificationList, replacer));
  }

  if (adminUsernameList.includes(userName)) {
    taskLogList = await prisma.taskLog.findMany({
      orderBy: [
        {
          updatedAt: "desc",
        },
      ],
    });

    taskLogInfoList = JSON.parse(JSON.stringify(taskLogList, replacer));
  }

  if (adminUsernameList.includes(userName)) {
    messageList = await prisma.message.findMany({
      orderBy: [
        {
          updatedAt: "desc",
        },
      ],
    });

    messageInfoList = JSON.parse(JSON.stringify(messageList, replacer));
  }

  return {
    props: { responseInfoList, fitbitNotificationInfoList, taskLogInfoList, messageInfoList, userInfo},
  };
}

export default function Dashboard({ responseInfoList, fitbitNotificationInfoList, taskLogInfoList, messageInfoList, userInfo}) {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [tabName, setTabName] = useState("Survey Response");

  const handleTabChange = (event, newTabName) => {
    setTabName(newTabName);
  };

  //logger.logToDB("main", {message: "test"});

  //const [value1, setValue1] = useState('');
  //const [value2, setValue2] = useState('');

  // status: enum mapping to three possible session states: "loading" | "authenticated" | "unauthenticated"
  if (status == "loading") return <div>loading...</div>;

  if (!session) {
    router.push("/");
    return null;
  }

  console.log(`session: ${JSON.stringify(session)}`);

  return (
    <div className={styles.container}>
      <Head>
        <title>Walk To Joy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ToggleButtonGroup
        value={tabName}
        exclusive
        onChange={handleTabChange}
        aria-label="tab name"
      >
        <ToggleButton value="Survey Response" aria-label="left aligned">
          Survey Response
        </ToggleButton>
        <ToggleButton
          value="Fitbit Subscription"
          aria-label="centered"
        >
          Fitbit Subscription
        </ToggleButton>
        <ToggleButton
          value="Task Log"
          aria-label="centered"
        >
          Task Log
        </ToggleButton>
        <ToggleButton
          value="Message"
          aria-label="centered"
        >
          Message
        </ToggleButton>
      </ToggleButtonGroup>

      {tabName == "Survey Response" ? (
        <SurveyResponseTable infoList={responseInfoList} />
      ) : null}
      
      {tabName == "Fitbit Subscription" ? (
        <FitbitSubscriptionTable infoList={fitbitNotificationInfoList} />
      ) : null}

      {tabName == "Task Log" ? (
        <TaskLogTable infoList={taskLogInfoList} />
      ) : null}

      {tabName == "Message" ? (
        <MessageTable infoList={messageInfoList} userInfo={userInfo} />
      ) : null}

      <main className={styles.main}></main>

      <footer className={styles.main}>
        <div>WalkToJoy Study</div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div>School of Information</div>
          <div>University of Michigan</div>
        </a>
      </footer>
    </div>
  );
}
