import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";


import TextField from "@mui/material/TextField";
/*
import logger from "../lib/logger";

*/

import { inspect } from "util";

import Link from "next/link";
import { useSession, signIn, signOut, getSession } from "next-auth/react";
import { useRouter } from "next/router";
import React, { Fragment, useState } from "react";
import Button from '@mui/material/Button';
import Divider from "@mui/material/Divider";
import prisma from "../lib/prisma.mjs";
import { DateTime } from "luxon";

function replacer(key, value) {
  if (typeof value === "Date") {
    return value.toString();
  }
  return value;
}

export async function getServerSideProps(ctx) {
  const session = await getSession(ctx);
  console.log(`main.getServerSideProps: session: ${JSON.stringify(session)}`);

  if (!session) {
    return {
      props: {userInfo:{}},
    };
  }

  let userName = session.user.name;

  const uniqueUser = await prisma.users.findFirst({
    where: { username: userName },
  });

  console.log(`main.getServerSideProps: user: ${JSON.stringify(uniqueUser)}`);

  const userInfo = JSON.parse(JSON.stringify(uniqueUser, replacer));

  return {
    props: { userInfo },
  };
}

export default function InfoEdit({ userInfo }) {
  const { data: session, status } = useSession();
  const router = useRouter();

  console.log(`InfoEdit.userInfo: ${JSON.stringify(userInfo)}`);

  const [preferredName, setPreferredName] = useState(
    userInfo != undefined && userInfo.preferredName != undefined ? userInfo.preferredName : ""
  );
  const [phone, setPhone] = useState(
    userInfo != undefined && userInfo.phone != undefined ? userInfo.phone : ""
  );

  // status: enum mapping to three possible session states: "loading" | "authenticated" | "unauthenticated"
  if (status == "loading") return <div>loading...</div>;

  if (!session) {
    router.push("/");
    return null;
  }

  console.log(`session: ${JSON.stringify(session)}`);
  //console.log(`InfoEdit userInfo.joinAt: ${userInfo.joinAt}`);

  async function updateInfo(
    username,
    info
  ) {
    console.log(`InfoEdit.updateInfo: ${username}`);
    console.log(`InfoEdit.updateInfo.info: ${JSON.stringify(info)}`);

    const result = await fetch(
      "/api/user?function_name=update_info",
      {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({...info, 
          username: username
        }),
      }
    ).then((r) => {
      return r.json();
    });

    return result;
  }

  function onSaveClick(event) {
    let preparationInfo = undefined;
    console.log(`onSaveClick: userInfo.joinAt ${userInfo.joinAt}`);
    if(userInfo.joinAt == null){
      preparationInfo = {
        preferredName,
        phone,
        joinAt: userInfo.joinAt == null? DateTime.utc().toISO(): null
      }
    }
    else{
      preparationInfo = {
        preferredName,
        phone
      }
    }

    console.log(`onSaveClick: updatedInfo preparation ${JSON.stringify(preparationInfo, null, 2)}`);

    updateInfo(
      userInfo.username,
      preparationInfo
    ).then((response) => {
      router.push("/main");
      return response;
    });
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Preferred Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Welcome to WalkToJoy Study!</h1>
        <h2>How should we call you?</h2>
        <div>
          <TextField
            fullWidth
            label="Preferred Name"
            id="fullWidth"
            value={preferredName}
            onChange={(event) => {
                console.log(`setPreferredName: ${event.currentTarget.value}`);
              setPreferredName(event.currentTarget.value);
              
            }}
          />
          <br />
          <Divider />
          <br />
          <Fragment>{
            false? <TextField
            fullWidth
            label="Phone Number"
            id="fullWidth"
            value={phone}
            
            onChange={(event) => {
                console.log(`setPhone: ${event.currentTarget.value}`);
              setPhone(event.currentTarget.value);
            }}
          />: null }</Fragment>
          
          <br />
          <br />
          <Button variant="contained" style={{ width: "100%" }} onClick={onSaveClick} >Save</Button>
        </div>
      </main>

      <footer className={styles.main}>
        <div>WalkToJoy Study</div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div>School of Information</div>
          <div>University of Michigan</div>
        </a>
      </footer>
    </div>
  );
}
