import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import "primereact/resources/themes/nova/theme.css"
import "primereact/resources/primereact.min.css";
import "primeicons/primeicons.css";
import 'primeflex/primeflex.css';

import logger from "../lib/logger";
import prisma from '../lib/prisma';

import Link from 'next/link';
import { useSession, signIn, signOut } from "next-auth/react"
import { useRouter } from 'next/router'
import React, { useState } from 'react';
import { InputText } from 'primereact/inputtext';
import { Password } from 'primereact/password';
import { Button } from 'primereact/button';


function replacer(key, value) {
  if (typeof value === 'Date') {
    return value.toString();
  }
  return value;
}

export const getServerSideProps = async ({ req }) => {
  // const token = req.headers.AUTHORIZATION
  // const userId = await getUserId(token)\

  const logs = await prisma.log.findMany();

  const logList = JSON.parse(JSON.stringify(logs, replacer));

  return {
    props : { logList }
  }
}


export default function Main({logList}) {

  const { data: session, status } = useSession();
  const router = useRouter();

  logger.logToDB("main", {message: "test"});

  //const [value1, setValue1] = useState('');
  //const [value2, setValue2] = useState('');

  

  // status: enum mapping to three possible session states: "loading" | "authenticated" | "unauthenticated"
  if (status == "loading") return <div>loading...</div>;

  if (!session){
    router.push('/');
    return null;
  }


  return (
    <div className={styles.container}>
      <Head>
        <title>Walk To Joy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        
      <div>
        <Link href="/home"><button>Personalize your Experience</button></Link><br /><br />
        <Link href="/home"><button>Complete the Baseline Survey</button></Link><br /><br />
        <Link href="/home"><button>Connect your Fitbit</button></Link><br /><br />
        <Link href="/home"><button>Disable Sedentary Notification on your Fitbit application</button></Link><br /><br />
      </div>
      <div>
        <p>1/4 complete</p>
        <p>Once all tasks are completed, your study will be activiated the upcoming Monday for the duration of 6 weeks.</p>

      </div>
        




      </main>

      <footer className={styles.main}>
        <div>
          WalkToJoy Study
        </div>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <div>School of Informaiton</div>
        <div>University of Michigan</div>
          
        </a>
      </footer>
    </div>
  )
}
